name: app-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - fastapi
  - uvicorn
  - gunicorn
  - xarray
  - dask
  - s3fs
  - numcodecs
  - pip
  - pip:
    - git+https://github.com/lsetiawan/xpublish.git@encode_error