channels:
  - conda-forge
dependencies:
  - python=3.8
  - python-blosc
  - cytoolz
  - lz4
  - nomkl
  - gevent
  - fastapi
  - aiofiles
  - uvicorn
  - gunicorn
  - redis-py
  - aioredis
  - msgpack-python
  - xarray
  - zarr
  - dask
  - dask-kubernetes
  - netcdf4
  - s3fs==2022.02.0
  - intake
  - intake-xarray
  - jinja2==3.0.3
  - numcodecs
  - datashader
  - hvplot
  - numba
  - numpy
  - xlrd
  - pyarrow
  - bottleneck
  - toolz
  - gspread
  - loguru
  - celery
  - pika
  - prometheus-fastapi-instrumentator
  - watchgod
