name: app-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - fastapi
  - uvicorn
  - gunicorn
  - xarray
  - dask
  - netcdf4
  - s3fs
  - numcodecs
  - datashader
  - fsspec
  - numba
  - numpy
  - pip
  - xlrd
  - fastparquet
  - pip:
    - git+https://github.com/jhamman/xpublish.git@master
    - gspread