name: app-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - python-blosc
  - cytoolz
  - lz4
  - nomkl
  - fastapi
  - aiofiles
  - uvicorn
  - gunicorn
  - redis-py
  - aioredis
  - msgpack-python
  - xarray
  - zarr
  - dask
  - dask-kubernetes
  - netcdf4
  - s3fs==0.5.2
  - fsspec==0.8.7
  - aiobotocore==1.2.1
  - intake
  - intake-xarray
  - numcodecs
  - datashader
  - hvplot
  - numba
  - numpy
  - pip
  - xlrd
  - pyarrow
  - bottleneck
  - toolz
  - gspread
  - loguru
  - celery
  - pika
  - prometheus-fastapi-instrumentator
  - pip=22
  - pip:
    - git+https://github.com/jhamman/xpublish.git@master
