# Default values for cava-media.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: cava-data
# fullnameOverride: cava-media
path: /data
development: false
service:
  targetPort: 80
  portName: http
  type: ClusterIP
  port: 80
  containerPort: 80
  servicePortName: http
image:
  repository: cormorack/cava-data
  tag: "set-by-chartpress"
  pullSecrets: []
  pullPolicy: Always
replicas: 1
resources: {}
env:
  - name: AWS_ACCESS_KEY_ID
    value: ""
  - name: AWS_SECRET_ACCESS_KEY
    value: ""
  - name: OOI_TOKEN
    value: ""
  - name: OOI_USERNAME
    value: ""
  - name: REDIS_HOST
    value: ""
  - name: REDIS_PORT
    value: ""
  - name: GOOGLE_SERVICE_JSON
    value: ""
restartPolicy: Always
nodeSelector: {}
ingress:
  expose: false

  # If secure, must provide tls
  secure: false

  # host: "test.example.com"
  host: ""

  # Adds tls for domain certification
  # Certificate must be created ahead of time
  # tls:
  #   secretName: cava-data-cert
  tls: {}

# CAVA Data Celery Workers
worker:
  replicas: 1
  nodeSelector: {}
  extra_env:
    - name: REDIS_URI
      value: "redis://redis-service"
    - name: RABBITMQ_URI
      value: "amqp://guest@rabbitmq-service:5672//"
  resources: {}
