name: Cava data PR Build

on:
  pull_request:
    paths-ignore:
      - README.md
      - "resources/helm/**"
      - "**/test-chart.yml"
      - ".ci-helpers/**"

env:
  DOCKER_ORG: cormorack
  IMAGE_NAME: cava-data
  CONDA_VERSION: 4.12.0-0
  PYTHON_VERSION: 3.8

jobs:
  # TODO: Need python tests build with fastapi ...
  docker-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Job Environment Variables
        run: |
          DOCKER_TAG=PR
          IMAGE_SPEC="${DOCKER_ORG}/${{ env.IMAGE_NAME }}:${DOCKER_TAG}"
          echo "IMAGE_SPEC=${IMAGE_SPEC}" >> "$GITHUB_ENV"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./resources/docker/Dockerfile
          push: false
          build-args: |
            CONDA_VERSION=${{ env.CONDA_VERSION }}
            echo "CONDA_VERSION=${CONDA_VERSION}" >> "$GITHUB_ENV"
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            echo "PYTHON_VERSION=${PYTHON_VERSION}" >> "$GITUB_ENV"
          tags: |
            ${{ env.IMAGE_SPEC }}